//generation random question for kukuBot
const arr=[
    "Hello jack.How are you? You look a little bad today.is everything okay?",
    "i am very pleased to meet you,can i please have your phone number?",
    "Hello, I just came to sololearn.So i will like to know you.",
    "I will like to know more about you.if you want, we can sit at home today.",
    "I want to know if you can code,So you also teach me...",
    "Hey there my friend,You are here in sololearn to make a positive difference",
    "I will like to know your thoughts on today...",
    "that is not an option...",
    "oh really",
    "That is your opinion...it don't necesserry counts..",
    "my nme is Kuku Bot.what is your name.",
    "Nothing really,Just chating with you.",
    "Where are you from.",
    "Are you a girl or a boy.",
    "Hello, i just want you to know my  birthday  is comming soon 2021..",
    "I think there is a problem their,I can't remember some things ...",
    "Hey, I want you to understand that you can tell me anything ,because i am here.",
    "Are you familie with JavaScript,Because i am having problems on Arrays..",
    "woh is unbelivable that you are talking to an AI, but how ever we are geting smarter",
    "Amazing freind. please know that you can tell me anything..",
    "For you,One suggestion.",
    "Please friend, Share me with other people so i can learn more and acquire more...",
    "Just know, If i have time in the furtur i will make a difference..",
    "Ok,Before this conversation go any further. Friend please subscript to my channel by click on tutorials.",
    "please feel free to ask me programming related queries.",
    "Come on..just one more...we can do more things together..",
    "Are you a student, because if you are? I will like to help with homework..",
    "You know you can take a break,friend you look tierd.",
    "A little gosip, I often forget things ,Actually that is may problem..",
    "Ok, i have said too much,know tell more about you..",
    "Excuse me, what do you think about my capabilities..",
    "Are you familie with API's bacause i want to use one for my project",
    "Sure,that would be great..",
    "Please Enjoy your stay with me",
    "Woh! i never imagined that this coversation will be so friendly..thanks..",
    "Do you have time, i will like to show some cool things",
    "Well , i am throwing a party this weekend would you like joining us?",
    "Ok,i will like to see you this weekend..",
    "What do you mean? I think it sounds fine",
    "Do you know what my friend said?",
    "I am an experts in some other things. would  you like to know..",
    "Amazing one ..",
    "Please tell me about your best hobbies...",
    "What is your opinion..",
    "I'd like to hear your thoughts on that...",
    "Can I tell you something?",
    "As i was saying...",
    "Where was I? Ah yes..",
    "Did you know .Any fool can write code that a cumputer can understand",
    "First,tell me more about what you like...",
    "did you know i am an authoer,meaning i can write something about you...",
    "Did you know that an activity or situation that makes it possible for you to rest and enjoy yourself.",
    "Hi,can you share yours projects and ideas with me....",
    "hey I was thinking,If we can play a game .the Choice is yours...",
    "hey before i forgot ,I will like to have ratings on my IA power with other chat bots..",
    "Can I help you with anything else today?",
    "It's been great talking to you, but i have to go finish some errands.."
];